### ISSUE TITLE
[Question] different apk sizes

### ISSUE THREAD

**Issue by FadeFx** [dmitriy-ilchenko/QrAndBarcodeScanner#154]
Why is the APK size on playstore smaller than on fdroid?

**Comment by deddyrumapea** [comment]
The APK size on Play Store is smaller than on F-Droid because of the different ways they handle app signing and compression. [Play Store uses Google’s app signing process which optimizes the APK size by removing unnecessary files and compressing resources](https://developer.android.com/topic/performance/reduce-apk-size)[1](https://developer.android.com/topic/performance/reduce-apk-size). [On the other hand, F-Droid does not use Google’s app signing process and does not compress resources](https://stackoverflow.com/questions/22389319/android-why-is-the-size-of-apk-file-smaller-than-the-entire-project)[2](https://stackoverflow.com/questions/22389319/android-why-is-the-size-of-apk-file-smaller-than-the-entire-project).

**Comment by deddyrumapea** [comment]
The APK size on Play Store is smaller than on F-Droid because of the different ways they handle app signing and compression. [Play Store uses Google’s app signing process which optimizes the APK size by removing unnecessary files and compressing resources](https://developer.android.com/topic/performance/reduce-apk-size). On the other hand, F-Droid does not use Google’s app signing process and does not compress resources.

**Comment by FadeFx** [comment]
OK, thanx for clearification
